version: "3.9"

services:
  flaskapp:
    build: .
    container_name: flask-app
    networks:
      - caddy
    labels:
      caddy: flask.borjabn-clase.duckdns.org
      caddy.reverse_proxy: "flask-app:5000"
    restart: unless-stopped

networks:
  caddy:
    external: true
